#!/bin/bash

# Get the absolute path of the current working directory
cwd=$(pwd -P)

# Print the absolute path of the current working directory
echo "The absolute path of the current working directory is: $cwd"
